source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp.views import IndexView, ArticleCreateView, ArticleView, \
    ArticleUpdateView, ArticleCommentCreateView, article_mass_action_view, CommentUpdateView, \
    ArticleDeleteView, CommentDeleteViews, ArticleLike, ArticleLikeView, ArticleUnLikeView, CommentLikeView, \
    CommentUnLikeView
from django.conf.urls.static import static
from django.conf import settings
# from accounts.views import login_view, logout_view
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', IndexView.as_view(), name='index'),
                  path('article/', include([
                      path('add/', ArticleCreateView.as_view(), name='article_create'),
                      path('<int:pk>/', ArticleView.as_view(), name='article_view'),
                      path('<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
                      path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
                      path('mass-action/', article_mass_action_view, name='article_mass_action'),
                      path('<int:pk>/comments/add/', ArticleCommentCreateView.as_view(),
                           name='article_comment_add'),
                      path('<int:pk>/like/', ArticleLikeView.as_view(), name='article_like'),
                      path('<int:pk>/unlike/', ArticleUnLikeView.as_view(), name='article_unlike')
                  ])),

                  path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
                  path('comment/<int:pk>/delete/', CommentDeleteViews.as_view(), name='comment_delete'),
                  path('<int:pk>/like/', CommentLikeView.as_view(), name='comment_like'),
                  path('<int:pk>/unlike/', CommentUnLikeView.as_view(), name='comment_unlike'),

                  path('accounts/', include('accounts.urls')),
                  path('api/v1/',include('api_v1.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

STATUS_CHOICES = [
    ('new', 'Не модерировано'),
    ('moderated', 'Модерировано'),
    ('rejected', 'Отклонено')
]


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок',
                             validators=[MinLengthValidator(10)])
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='articles',
                               verbose_name='Автор')
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='new', verbose_name='Модерация')
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True, verbose_name='Теги')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    publish_at = models.DateTimeField(verbose_name="Время публикации", blank=True, default=timezone.now)
    like_count = models.IntegerField(verbose_name='Счетчик лайков', default=0)

    def save(self, **kwargs):
        if not self.publish_at:
            if not self.pk:
                self.publish_at = timezone.now()
            else:
                self.publish_at = Article.objects.get(pk=self.pk).publish_at
        super().save(**kwargs)

    def liked_by(self, user):
        likes = self.likes.filter(user=user)
        return likes.count() > 0

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='comments',
                                on_delete=models.CASCADE, verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='comments',
                               verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    like_count = models.IntegerField(verbose_name='Счетчик лайков', default=0)

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def liked_by(self, user):
        likes = self.likes.filter(user=user)
        return likes.count() > 0


class Tag(models.Model):
    name = models.CharField(max_length=31, verbose_name='Тег')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class ArticleLike(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='article_likes',
                             verbose_name='Пользователь', on_delete=models.CASCADE)
    article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Статья')

    def __str__(self):
        return f'{self.user.username} - {self.article.title}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки статей'


class CommentLike(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='comment_likes',
                             verbose_name='Пользователь', on_delete=models.CASCADE)
    comment = models.ForeignKey('webapp.Comment', on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Комменатрий')

    def __str__(self):
        return f'{self.user.username} - {self.comment.text}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки комментариев'

source/webapp/views/article_views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.timezone import make_naive
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import View

from webapp.models import Article, Tag, ArticleLike
from webapp.forms import ArticleForm, BROWSER_DATETIME_FORMAT
from .base_views import SearchView


class IndexView(SearchView):
    template_name = 'article/index.html'
    context_object_name = 'articles'
    paginate_by = 2
    paginate_orphans = 0
    model = Article
    ordering = ['-created_at']
    search_fields = ['title__icontains', 'author__i contains']

    def get_queryset(self):
        data = super().get_queryset()
        if not self.request.GET.get('is_admin', None):
            data = data.filter(status='moderated')
        return data


@login_required
def article_mass_action_view(request):
    if request.method == 'POST':
        ids = request.POST.getlist('selected_articles', [])
        if 'delete' in request.POST:
            Article.objects.filter(id__in=ids).delete()
    return redirect('index')


class ArticleView(DetailView):
    template_name = 'article/article_view.html'
    model = Article
    paginate_comments_by = 2
    paginate_orphans = 0

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        comments, page, is_paginated = self.paginate_comments(self.object)
        context['comments'] = comments
        context['page_obj'] = page
        context['is_paginated'] = is_paginated  # page.has_other_pages()
        print(self.args)
        print(self.kwargs)
        return context

    def paginate_comments(self, article):
        comments = article.comments.all().order_by('-created_at')
        if comments.count() > 0:
            paginator = Paginator(comments, self.paginate_comments_by, orphans=self.paginate_orphans)
            page_number = self.request.GET.get('page', 1)
            page = paginator.get_page(page_number)
            is_paginated = paginator.num_pages > 1
            return page.object_list, page, is_paginated
        else:
            return comments, None, False


class ArticleCreateView(LoginRequiredMixin, CreateView):
    template_name = 'article/article_create.html'
    form_class = ArticleForm
    model = Article

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response
    #
    # def get_success_url(self):
    #     return reverse('article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user
        article.save()
        form.save_m2m()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('article_view', pk=article.pk)


class ArticleUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'article/article_update.html'
    form_class = ArticleForm
    model = Article
    permission_required = 'webapp.change_article'

    def has_permission(self):
        article = self.get_object()
        return super().has_permission() or article.author == self.request.user

    # def dispatch(self, request, *args, **kwargs):
    #     user = request.user
    #     if not user.is_authenticated:
    #         return redirect('accounts:login')
    #     if not user.has_perm('webapp.change_article'):
    #         raise PermissionDenied
    #     return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {'publish_at': make_naive(self.object.publish_at) \
            .strftime(BROWSER_DATETIME_FORMAT)}

    # def form_valid(self, form):
    #     response = super().form_valid(form)
    #     tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
    #     form.instance.tags.add(tag)
    #     return response

    # def get_success_url(self):
    #     return reverse('article_view', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        article = form.save()
        tag, _ = Tag.objects.get_or_create(name=self.request.user.username)
        article.tags.add(tag)
        return redirect('article_view', pk=article.pk)


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'article/delete_article.html'
    model = Article
    success_url = reverse_lazy('index')

    # permission_required = 'webapp.delete_article'

    def test_func(self):
        return self.request.user.has_perm('webapp.delete_article') or \
               self.get_object().author == self.request.user


class ArticleLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)
        if created:
            article.like_count += 1
            article.save()
            return HttpResponse(article.like_count)
        else:
            return HttpResponseForbidden()


class ArticleUnLikeView(LoginRequiredMixin ,View):
    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs.get('pk'))
        like = get_object_or_404(article.likes, user=request.user)
        like.delete()
        article.like_count -= 1
        article.save()
        return HttpResponse(article.like_count)

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Comment, Article, CommentLike
from webapp.forms import ArticleCommentForm


# from .base_views import DeleteView


# from .base_views import UpdateView


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment/comment_create.html'
    form_class = ArticleCommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        form.save_m2m()
        return redirect('article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    permission_required = 'webapp.change_comment'
    template_name = 'comment/comment_update.html'
    form_class = ArticleCommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteViews(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.article.pk})


class CommentLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs.get('pk'))
        like, created = CommentLike.objects.get_or_create(comment=comment, user=request.user)
        if created:
            comment.like_count += 1
            comment.save()
            return HttpResponse(comment.like_count)
        else:
            return HttpResponseForbidden()


class CommentUnLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs.get('pk'))
        like = get_object_or_404(comment.likes, user=request.user)
        like.delete()
        comment.like_count -= 1
        comment.save()
        return HttpResponse(comment.like_count)

source/webapp/templates/partial/article_list.html
{% load likes %}
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

<form action="{% url "article_mass_action" %}" method="post">
    {% csrf_token %}
<p class="mass-actions"><input type="submit" name="delete" value="Delete selected"></p>

{% for article in articles %}
    <div class="box">
        <h3><a href="{% url "article_view" article.pk %}">{{ article.title }}</a></h3>
        <p>
            <label for="selected_articles-{{ article.pk }}">Select: </label>
            <input type="checkbox" name="selected_articles"
                   id="selected_articles-{{ article.pk }}" value="{{ article.pk }}">
        </p>
        <p>Cтатус: ({{ article.status }} | {{ article.get_status_display }})</p>
        <p>
            <a href="{% url 'accounts:detail' article.author_id %}">{{ article.author }}</a>| {{ article.created_at|date:"d.m.Y H:i:s" }}
        </p>
        <p>Publish at: {{ article.publish_at|date:"d.m.Y H:i:s" }}</p>
        {% if perms.webapp.change_article or article.author == request.user %}
            <p><a href="{% url 'article_update' article.pk %}">Update</a></p>
        {% endif %}
        {% if perms.webapp.change_article or article.author == request.user %}
            <p><a href="{% url 'article_delete' article.pk %}">Delete</a></p>
        {% endif %}
        {% if user.is_authenticated %}
            <p>
                <span class="counter">{{ article.like_count }}</span>
                {% with article|liked_by:user as liked %}
                    <a class="{% if liked %}hidden{% endif %} like" href="{% url 'article_like' article.pk %}">Like</a>
                    <a class="{% if not liked %}hidden{% endif %} unlike" href="{% url 'article_unlike' article.pk %}">Unlike</a>
                {% endwith %}
            </p>
        {% endif %}
    </div>
{% endfor %}
</form>

{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}

source/webapp/templates/partial/form.field.html
{% load widget_tweaks %}

<label for="{{ field.id_for_label }}">
    {% if field.field.required %}
        <span class="red">*</span>
    {% endif %}
    {{ field.label }}:
</label>
<br/>
{% if field|field_type == 'modelmultiplechoicefield' %}
    {{ field|add_class:'form-checkboxes'|add_error_class:'form-error' }}
{% else %}
    {{ field|add_class:'form-input'|add_error_class:'form-error' }}
{% endif %}
<br/>
{% for error in field.errors %}
    <p class="error">{{ error }}</p>
{% endfor %}
<br/>

source/webapp/templates/partial/form.html
{% if not fields_only %}
    <form action="{{ action_url }}" method="{{ form_method }}" enctype="{{ enctype }}" id="{{ form_id }}">
        {% csrf_token %}
{% endif %}

        {% for error in form.non_field_errors %}
            <p class="error">{{ error }}</p>
        {% endfor %}

        {% for field in form %}
            {% include 'partial/form_field.html' %}
        {% endfor %}

{% if not fields_only %}
        <br/>
        <input type="submit" value="{{ button_text|default:"Submit" }}"/>
    </form>
{% endif %}

source/webapp/templates/partial/pagination.html
{% load page_utils %}

<div class="pagination">
    <span class="step-links">
        <a href="?{{ request|page_query_string:1 }}">&laquo; В начало</a>

        {% if page_obj.has_previous %}
            <a href="?{{ request|page_query_string:page_obj.previous_page_number }}">Назад</a>
        {% else %}
            <span class="page-disabled">Назад</span>
        {% endif %}


        <form class="current-page" method="get">
            <label for="page">
                {% for key, value in request.GET.items %}
                    {% if not key == 'page' %}
                        <input type="hidden" name="{{ key }}" value="{{ value }}">
                    {% endif %}
                {% endfor %}
                Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                из {{ page_obj.paginator.num_pages }}.
            </label>
        </form>

        {% if page_obj.has_next %}
            <a href="?{{ request|page_query_string:page_obj.next_page_number }}">Далее</a>
        {% else %}
            <span class="page-disabled">Далее</span>
        {% endif %}

        <a href="?{{ request|page_query_string:page_obj.paginator.num_pages }}">В конец &raquo;</a>
    </span>
</div>