source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('<int:pk>/password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp.views import IndexView, ArticleCreateView, ArticleView, \
    ArticleUpdateView, ArticleCommentCreateView, article_mass_action_view, CommentUpdateView, \
    ArticleDeleteView, CommentDeleteViews, ArticleLike, ArticleLikeView, ArticleUnLikeView, CommentLikeView, \
    CommentUnLikeView
from django.conf.urls.static import static
from django.conf import settings
# from accounts.views import login_view, logout_view
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', IndexView.as_view(), name='index'),
                  path('article/', include([
                      path('add/', ArticleCreateView.as_view(), name='article_create'),
                      path('<int:pk>/', ArticleView.as_view(), name='article_view'),
                      path('<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
                      path('<int:pk>/delete/', ArticleDeleteView.as_view(), name='article_delete'),
                      path('mass-action/', article_mass_action_view, name='article_mass_action'),
                      path('<int:pk>/comments/add/', ArticleCommentCreateView.as_view(),
                           name='article_comment_add'),
                      path('<int:pk>/like/', ArticleLikeView.as_view(), name='article_like'),
                      path('<int:pk>/unlike/', ArticleUnLikeView.as_view(), name='article_unlike')
                  ])),

                  path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment_update'),
                  path('comment/<int:pk>/delete/', CommentDeleteViews.as_view(), name='comment_delete'),
                  path('<int:pk>/like/', CommentLikeView.as_view(), name='comment_like'),
                  path('<int:pk>/unlike/', CommentUnLikeView.as_view(), name='comment_unlike'),

                  path('accounts/', include('accounts.urls')),
                  path('api/v1/',include('api_v1.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

STATUS_CHOICES = [
    ('new', 'Не модерировано'),
    ('moderated', 'Модерировано'),
    ('rejected', 'Отклонено')
]


class Article(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок',
                             validators=[MinLengthValidator(10)])
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='articles',
                               verbose_name='Автор')
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='new', verbose_name='Модерация')
    tags = models.ManyToManyField('webapp.Tag', related_name='articles', blank=True, verbose_name='Теги')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    publish_at = models.DateTimeField(verbose_name="Время публикации", blank=True, default=timezone.now)
    like_count = models.IntegerField(verbose_name='Счетчик лайков', default=0)

    def save(self, **kwargs):
        if not self.publish_at:
            if not self.pk:
                self.publish_at = timezone.now()
            else:
                self.publish_at = Article.objects.get(pk=self.pk).publish_at
        super().save(**kwargs)

    def liked_by(self, user):
        likes = self.likes.filter(user=user)
        return likes.count() > 0

    def __str__(self):
        return "{}. {}".format(self.pk, self.title)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey('webapp.Article', related_name='comments',
                                on_delete=models.CASCADE, verbose_name='Статья')
    text = models.TextField(max_length=400, verbose_name='Комментарий')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_DEFAULT, default=1, related_name='comments',
                               verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    like_count = models.IntegerField(verbose_name='Счетчик лайков', default=0)

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def liked_by(self, user):
        likes = self.likes.filter(user=user)
        return likes.count() > 0


class Tag(models.Model):
    name = models.CharField(max_length=31, verbose_name='Тег')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


class ArticleLike(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='article_likes',
                             verbose_name='Пользователь', on_delete=models.CASCADE)
    article = models.ForeignKey('webapp.Article', on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Статья')

    def __str__(self):
        return f'{self.user.username} - {self.article.title}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки статей'


class CommentLike(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='comment_likes',
                             verbose_name='Пользователь', on_delete=models.CASCADE)
    comment = models.ForeignKey('webapp.Comment', on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Комменатрий')

    def __str__(self):
        return f'{self.user.username} - {self.comment.text}'

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки комментариев'

source/webapp/views/base_views.py
from django.db.models import Q
from django.views.generic import View, TemplateView, ListView, ListView as DjangoListView
from django.shortcuts import render, redirect, get_object_or_404

from webapp.forms import SimpleSearchForm


class FormView(View):
    form_class = None
    template_name = None
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_context_data(self, **kwargs):
        return kwargs

    def get_redirect_url(self):
        return self.redirect_url


class CustomListView(TemplateView):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_queryset()
        return context

    def get_queryset(self):
        return self.model.objects.all()


class SearchView(DjangoListView):
    search_form_class = SimpleSearchForm
    search_form_field = 'search'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value(self.search_form)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['search_form'] = self.search_form
        context['search_value'] = self.search_value
        return context

    def get_queryset(self):
        data = super().get_queryset()
        query = self.get_query(self.search_value)
        data = data.filter(query)
        return data

    def get_search_form(self):
        return self.search_form_class(data=self.request.GET)

    def get_search_value(self, form):
        search_value = None
        if form.is_valid():
            search_value = form.cleaned_data.get(self.search_form_field, None)
        return search_value

    def get_query(self, search_value):
        query = Q()
        if search_value:
            for field in self.search_fields:
                kwargs = {field: search_value}
                query = query | Q(**kwargs)
        return query


class DetailView(TemplateView):
    context_key = 'object'
    model = None
    key_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object()
        return context

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)


class CreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class UpdateView(View):
    form_class = None
    template_name = None
    redirect_url = ''
    model = None
    key_kwarg = 'pk'
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_form(self):
        form_kwargs = self.get_form_kwargs()
        form = self.form_class(**form_kwargs)
        return form

    def get_form_kwargs(self):
        kwargs = {'instance': self.object}
        if self.request.method == 'POST':
            kwargs['data'] = self.request.POST
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context=context)

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_context_data(self, **kwargs):
        context = self.kwargs.copy()
        context[self.context_key] = self.object
        context.update(kwargs)
        return context

    def get_redirect_url(self):
        return self.redirect_url


class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

source/webapp/views/comment_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.models import Comment, Article, CommentLike
from webapp.forms import ArticleCommentForm


# from .base_views import DeleteView


# from .base_views import UpdateView


class ArticleCommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = 'comment/comment_create.html'
    form_class = ArticleCommentForm

    def form_valid(self, form):
        article = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        comment = form.save(commit=False)
        comment.article = article
        comment.author = self.request.user
        comment.save()
        form.save_m2m()
        return redirect('article_view', pk=article.pk)


class CommentUpdateView(PermissionRequiredMixin, UpdateView):
    model = Comment
    permission_required = 'webapp.change_comment'
    template_name = 'comment/comment_update.html'
    form_class = ArticleCommentForm
    permission_required = 'webapp.change_comment'

    def has_permission(self):
        comment = self.get_object()
        return super().has_permission() or comment.author == self.request.user

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.article.pk})


class CommentDeleteViews(PermissionRequiredMixin, DeleteView):
    model = Comment
    permission_required = 'webapp.delete_comment'

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('article_view', kwargs={'pk': self.object.article.pk})


class CommentLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs.get('pk'))
        like, created = CommentLike.objects.get_or_create(comment=comment, user=request.user)
        if created:
            comment.like_count += 1
            comment.save()
            return HttpResponse(comment.like_count)
        else:
            return HttpResponseForbidden()


class CommentUnLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        comment = get_object_or_404(Comment, pk=kwargs.get('pk'))
        like = get_object_or_404(comment.likes, user=request.user)
        like.delete()
        comment.like_count -= 1
        comment.save()
        return HttpResponse(comment.like_count)

source/webapp/templates/article/article_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Create{% endblock %}
{% block content %}
    <h1>Create Article</h1>

    {% url "article_create" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' %}


{#        {% for field in form %}#}
{#            {% include 'partial/form.field.html' %}#}
{#        {% endfor %}#}

{#        {% include 'partial/form.field.html' with field=form.title %}#}
{#        {% include 'partial/form.field.html' with field=form.text %}#}
{#        {% include 'partial/form.field.html' with field=form.author %}#}
{#        {% include 'partial/form.field.html' with field=form.status %}#}
{% endblock %}
{% block scripts %}
    <script type="application/javascript" src="{% static "js/create_article.js" %}"></script>
{% endblock %}

source/webapp/templates/article/article_update.html
{% extends 'base.html' %}
{% block title %}Update{% endblock %}
{% block menu %}
    <li><a href="{% url 'article_view' article.pk %}">Cancle</a></li>
{% endblock %}


{% block content %}
    <h1>Update Article</h1>

    {% url "article_update" pk=article.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' button_text='Update' %}

{% endblock %}

source/webapp/templates/article/article_view.html
{% extends 'base.html' %}
{% load likes %}
{% block title %}View{% endblock %}

{% block menu %}
    {% if perms.webapp.change_article %}
        <li><a href="{% url 'article_update' article.pk %}">Update</a></li>
    {% endif %}
    {% if perms.webapp.delete_article %}
        <li><a href="{% url 'article_delete' article.pk %}">Delete</a></li>
    {% endif %}
        <li><a href="{% url 'article_comment_add' article.pk %}">Add Comment</a></li>
{% endblock %}

{% block content %}
    <div class="box">
        <h1>{{ article.title }}</h1>
        <p>{{ article.text }}</p>
        <p>By:
            <a href="{% url 'accounts:detail' article.author_id %}">{{ article.author }}</a>
            | {{ article.created_at|date:"d.m.Y H:i:s" }}
        </p>

        <p>Published at: {{ article.publish_at|date:"d.m.Y H:i:s" }}</p>

        <p>Tags: {% for tags in article.tags.all %}{{tags.name}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        {% if user.is_authenticated %}
            <p>
                <span class="counter">{{ article.like_count }}</span>
                {% with article|liked_by:user as liked %}
                    <a class="{% if liked %}hidden{% endif %} like" href="{% url 'article_like' article.pk %}">Like</a>
                    <a class="{% if not liked %}hidden{% endif %} unlike" href="{% url 'article_unlike' article.pk %}">Unlike</a>
                {% endwith %}
            </p>
        {% endif %}
        <hr>
        <h3>Comments: </h3>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% for comment in comments %}
            <div class="box">
                <h4>
                    <a href="{% url 'accounts:detail' comment.author_id %}">{{ comment.author }}</a>
                    ({{ comment.created_at }})
                </h4>
                <div class="pre">{{ comment.text }}</div>
                {% if perms.webapp.change_comment or comment.author == request.user %}
                    <p><a href="{% url 'comment_update' comment.pk %}">Update </a></p>
                {% endif %}
                {% if perms.webapp.delete_comment or comment.author == request.user %}
                    <p><a href="{% url 'comment_delete' comment.pk %}">Delete </a></p>
                {% endif %}
                {% if user.is_authenticated %}
                    <p>
                        <span class="counter">{{ comment.like_count }}</span>
                        {% with comment|liked_by:user as liked %}
                            <a class="{% if liked %}hidden{% endif %} like" href="{% url 'comment_like' comment.pk %}">Like</a>
                            <a class="{% if not liked %}hidden{% endif %} unlike" href="{% url 'comment_unlike' comment.pk %}">Unlike</a>
                        {% endwith %}
                    </p>
                {% endif %}
            </div>
        {% empty %}
            <p>No comments</p>
        {% endfor %}
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/article/delete_article.html
{% extends "base.html" %}
{% block title %}Delete Article{% endblock %}
{% block menu %}
    <li><a href="{% url 'article_view' article.pk %}">Cancel</a></li>
{% endblock %}
{% block content %}
    <h1>Are you sure want to delete article "{{ article.title }}"?</h1>
    <form action="{% url "article_delete" article.pk %}" method="post">
        {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url "article_view" article.pk %}">Cancel</a></p>
    </form>
{% endblock %}

source/webapp/templates/article/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Hello{% endblock %}

{% block content %}
    <h1>My first blog!!!</h1>

    {% include 'partial/article_list.html' %}

{% endblock %}
{% block scripts %}
    <script type="application/javascript" src="{% static "js/likes.js" %}"></script>
{% endblock %}